/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:f744eb26-5026-4d20-a097-792d89f71191",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_WE51dAPcc",
    "aws_user_pools_web_client_id": "5s5oilv77etdaao4b519r6mjbb",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://n2agoyzcbngo7i5ng6vbdswhmi.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-xzyjgvxhk5f45fhjakjvbgfk3m",
    "aws_user_files_s3_bucket": "starterkit37e5cc22c8a74632bcd5ff54d115b4c7223702-staging",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
